--------------------------------- MAGNITUDE ANALYSIS -----------------------------------

-- Compare the measure values by categories.
-- It help us to understand the importance of different categories.

-- Find the total customers by Countries
SELECT 
COUNT(Customer_id) AS Total_Customer,
country
FROM Gold.dim_customers
GROUP BY country
ORDER BY Total_Customer DESC
-- Find total Customer by gender
SELECT 
COUNT(Customer_id) AS Total_Customer,
Gender
FROM Gold.dim_customers
GROUP BY gender
ORDER BY Total_Customer DESC
 
-- Find total product by category
SELECT
COUNT(Product_Key) AS Total_Product,
Category
FROM Gold.dim_Products
GROUP BY Category
ORDER BY Total_Product DESC

-- What is the average costs in each category?
SELECT
AVG(Cost) AS Avg_Cost,
Category
FROM Gold.dim_Products
GROUP BY Category
ORDER BY Avg_Cost DESC

-- What is the total revenue generated for each category?
SELECT
SUM(f.Sales_Amount) Total_Revenue,
p.Category
FROM Gold.fact_Sales f
LEFT JOIN Gold.dim_Products p
ON  p.Product_Key = f.Product_key
GROUP BY p.Category
Order BY Total_Revenue DESC

-- Find total revenue is generated by each customer
SELECT
c.customer_key,
c.First_Name,
c.Last_Name,
SUM(f.Sales_Amount) AS total_revenue
FROM Gold.fact_Sales f
LEFT JOIN Gold.dim_customers c
ON c.customer_key = f.Customer_key
GROUP BY 
c.customer_key,
c.First_Name,
c.Last_Name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?

SELECT
c.country,
SUM(f.Quantity) AS total_sold_items
FROM Gold.fact_Sales f
LEFT JOIN Gold.dim_customers c
ON c.customer_key = f.Customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC

